che:
  image: codenvy/che
  stdin_open: true
  tty: true
  labels:
    "Version": "v0.0.1"
  ports:
    - "8080:8080"
    - "49152-49162:49152-49162"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  network_mode: "host"


